name: Запуск линтера API при pull request в main ветку

on:
  pull_request:
    branches: [ main ]

jobs:
  spectral-lint:
    name: Run Spectral
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Spectral Linting
        uses: stoplightio/spectral-action@v0.8.11

