name: Запуск линтера Api при pull request в main ветку
 
on: 
  - pull_request 


jobs: 
  build: 
    name: Run Spectral 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: stoplightio/spectral-action@latest
        with: 
          file_glob: openapi.yaml
          fail_on: "warn"
          spectral_ruleset: '.spectral.yaml'
