on:
  - push
  - pull_request
name: CI
jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Spectral Linting
        uses: stoplightio/spectral-action@v0.8.11