name: Запуск линтера API при PR в main

on:
  pull_request:
    branches: [main]

jobs:
  spectral-lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code (обязательный шаг!)
        uses: actions/checkout@v4  
        with:
          fetch-depth: 0  

      - name: Run Spectral
        uses: stoplightio/spectral-action@latest 
        with:
          file_glob: './openapi.yaml'
          spectral_ruleset: './.spectral.yaml'