name: API Validation
on: [pull_request]
jobs:
  spectral:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: stoplightio/spectral-action@v5
        with:
          file_glob: 'openapi.yaml'
          spectral_ruleset: '.spectral.yaml'