# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
    
      - name: Run 'spectral lint' for default file, 'openapi-spec.yml'
        uses: ./
        with:
          file_path: api/openapi.yaml
